package club.ak.work.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MeasurementDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public MeasurementDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNull() {
            addCriterion("online_date is null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNotNull() {
            addCriterion("online_date is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateEqualTo(Date value) {
            addCriterion("online_date =", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotEqualTo(Date value) {
            addCriterion("online_date <>", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThan(Date value) {
            addCriterion("online_date >", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThanOrEqualTo(Date value) {
            addCriterion("online_date >=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThan(Date value) {
            addCriterion("online_date <", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThanOrEqualTo(Date value) {
            addCriterion("online_date <=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIn(List<Date> values) {
            addCriterion("online_date in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotIn(List<Date> values) {
            addCriterion("online_date not in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateBetween(Date value1, Date value2) {
            addCriterion("online_date between", value1, value2, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotBetween(Date value1, Date value2) {
            addCriterion("online_date not between", value1, value2, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlIsNull() {
            addCriterion("test_create_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlIsNotNull() {
            addCriterion("test_create_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlEqualTo(String value) {
            addCriterion("test_create_sql =", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlNotEqualTo(String value) {
            addCriterion("test_create_sql <>", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlGreaterThan(String value) {
            addCriterion("test_create_sql >", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_create_sql >=", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlLessThan(String value) {
            addCriterion("test_create_sql <", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlLessThanOrEqualTo(String value) {
            addCriterion("test_create_sql <=", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlLike(String value) {
            addCriterion("test_create_sql like", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlNotLike(String value) {
            addCriterion("test_create_sql not like", value, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlIn(List<String> values) {
            addCriterion("test_create_sql in", values, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlNotIn(List<String> values) {
            addCriterion("test_create_sql not in", values, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlBetween(String value1, String value2) {
            addCriterion("test_create_sql between", value1, value2, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateSqlNotBetween(String value1, String value2) {
            addCriterion("test_create_sql not between", value1, value2, "testCreateSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlIsNull() {
            addCriterion("test_create_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlIsNotNull() {
            addCriterion("test_create_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlEqualTo(String value) {
            addCriterion("test_create_rollback_sql =", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlNotEqualTo(String value) {
            addCriterion("test_create_rollback_sql <>", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlGreaterThan(String value) {
            addCriterion("test_create_rollback_sql >", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_create_rollback_sql >=", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlLessThan(String value) {
            addCriterion("test_create_rollback_sql <", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("test_create_rollback_sql <=", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlLike(String value) {
            addCriterion("test_create_rollback_sql like", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlNotLike(String value) {
            addCriterion("test_create_rollback_sql not like", value, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlIn(List<String> values) {
            addCriterion("test_create_rollback_sql in", values, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlNotIn(List<String> values) {
            addCriterion("test_create_rollback_sql not in", values, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlBetween(String value1, String value2) {
            addCriterion("test_create_rollback_sql between", value1, value2, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestCreateRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("test_create_rollback_sql not between", value1, value2, "testCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlIsNull() {
            addCriterion("test_alter_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlIsNotNull() {
            addCriterion("test_alter_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlEqualTo(String value) {
            addCriterion("test_alter_sql =", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlNotEqualTo(String value) {
            addCriterion("test_alter_sql <>", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlGreaterThan(String value) {
            addCriterion("test_alter_sql >", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_alter_sql >=", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlLessThan(String value) {
            addCriterion("test_alter_sql <", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlLessThanOrEqualTo(String value) {
            addCriterion("test_alter_sql <=", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlLike(String value) {
            addCriterion("test_alter_sql like", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlNotLike(String value) {
            addCriterion("test_alter_sql not like", value, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlIn(List<String> values) {
            addCriterion("test_alter_sql in", values, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlNotIn(List<String> values) {
            addCriterion("test_alter_sql not in", values, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlBetween(String value1, String value2) {
            addCriterion("test_alter_sql between", value1, value2, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterSqlNotBetween(String value1, String value2) {
            addCriterion("test_alter_sql not between", value1, value2, "testAlterSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlIsNull() {
            addCriterion("test_alter_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlIsNotNull() {
            addCriterion("test_alter_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlEqualTo(String value) {
            addCriterion("test_alter_rollback_sql =", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlNotEqualTo(String value) {
            addCriterion("test_alter_rollback_sql <>", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlGreaterThan(String value) {
            addCriterion("test_alter_rollback_sql >", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_alter_rollback_sql >=", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlLessThan(String value) {
            addCriterion("test_alter_rollback_sql <", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("test_alter_rollback_sql <=", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlLike(String value) {
            addCriterion("test_alter_rollback_sql like", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlNotLike(String value) {
            addCriterion("test_alter_rollback_sql not like", value, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlIn(List<String> values) {
            addCriterion("test_alter_rollback_sql in", values, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlNotIn(List<String> values) {
            addCriterion("test_alter_rollback_sql not in", values, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlBetween(String value1, String value2) {
            addCriterion("test_alter_rollback_sql between", value1, value2, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestAlterRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("test_alter_rollback_sql not between", value1, value2, "testAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlIsNull() {
            addCriterion("test_update_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlIsNotNull() {
            addCriterion("test_update_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlEqualTo(String value) {
            addCriterion("test_update_sql =", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlNotEqualTo(String value) {
            addCriterion("test_update_sql <>", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlGreaterThan(String value) {
            addCriterion("test_update_sql >", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_update_sql >=", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlLessThan(String value) {
            addCriterion("test_update_sql <", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlLessThanOrEqualTo(String value) {
            addCriterion("test_update_sql <=", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlLike(String value) {
            addCriterion("test_update_sql like", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlNotLike(String value) {
            addCriterion("test_update_sql not like", value, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlIn(List<String> values) {
            addCriterion("test_update_sql in", values, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlNotIn(List<String> values) {
            addCriterion("test_update_sql not in", values, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlBetween(String value1, String value2) {
            addCriterion("test_update_sql between", value1, value2, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateSqlNotBetween(String value1, String value2) {
            addCriterion("test_update_sql not between", value1, value2, "testUpdateSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlIsNull() {
            addCriterion("test_update_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlIsNotNull() {
            addCriterion("test_update_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlEqualTo(String value) {
            addCriterion("test_update_rollback_sql =", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlNotEqualTo(String value) {
            addCriterion("test_update_rollback_sql <>", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlGreaterThan(String value) {
            addCriterion("test_update_rollback_sql >", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_update_rollback_sql >=", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlLessThan(String value) {
            addCriterion("test_update_rollback_sql <", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("test_update_rollback_sql <=", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlLike(String value) {
            addCriterion("test_update_rollback_sql like", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlNotLike(String value) {
            addCriterion("test_update_rollback_sql not like", value, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlIn(List<String> values) {
            addCriterion("test_update_rollback_sql in", values, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlNotIn(List<String> values) {
            addCriterion("test_update_rollback_sql not in", values, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlBetween(String value1, String value2) {
            addCriterion("test_update_rollback_sql between", value1, value2, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestUpdateRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("test_update_rollback_sql not between", value1, value2, "testUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlIsNull() {
            addCriterion("test_insert_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlIsNotNull() {
            addCriterion("test_insert_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlEqualTo(String value) {
            addCriterion("test_insert_sql =", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlNotEqualTo(String value) {
            addCriterion("test_insert_sql <>", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlGreaterThan(String value) {
            addCriterion("test_insert_sql >", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_insert_sql >=", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlLessThan(String value) {
            addCriterion("test_insert_sql <", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlLessThanOrEqualTo(String value) {
            addCriterion("test_insert_sql <=", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlLike(String value) {
            addCriterion("test_insert_sql like", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlNotLike(String value) {
            addCriterion("test_insert_sql not like", value, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlIn(List<String> values) {
            addCriterion("test_insert_sql in", values, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlNotIn(List<String> values) {
            addCriterion("test_insert_sql not in", values, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlBetween(String value1, String value2) {
            addCriterion("test_insert_sql between", value1, value2, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertSqlNotBetween(String value1, String value2) {
            addCriterion("test_insert_sql not between", value1, value2, "testInsertSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlIsNull() {
            addCriterion("test_insert_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlIsNotNull() {
            addCriterion("test_insert_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlEqualTo(String value) {
            addCriterion("test_insert_rollback_sql =", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlNotEqualTo(String value) {
            addCriterion("test_insert_rollback_sql <>", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlGreaterThan(String value) {
            addCriterion("test_insert_rollback_sql >", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_insert_rollback_sql >=", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlLessThan(String value) {
            addCriterion("test_insert_rollback_sql <", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("test_insert_rollback_sql <=", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlLike(String value) {
            addCriterion("test_insert_rollback_sql like", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlNotLike(String value) {
            addCriterion("test_insert_rollback_sql not like", value, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlIn(List<String> values) {
            addCriterion("test_insert_rollback_sql in", values, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlNotIn(List<String> values) {
            addCriterion("test_insert_rollback_sql not in", values, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlBetween(String value1, String value2) {
            addCriterion("test_insert_rollback_sql between", value1, value2, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestInsertRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("test_insert_rollback_sql not between", value1, value2, "testInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlIsNull() {
            addCriterion("test_delete_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlIsNotNull() {
            addCriterion("test_delete_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlEqualTo(String value) {
            addCriterion("test_delete_sql =", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlNotEqualTo(String value) {
            addCriterion("test_delete_sql <>", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlGreaterThan(String value) {
            addCriterion("test_delete_sql >", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_delete_sql >=", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlLessThan(String value) {
            addCriterion("test_delete_sql <", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlLessThanOrEqualTo(String value) {
            addCriterion("test_delete_sql <=", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlLike(String value) {
            addCriterion("test_delete_sql like", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlNotLike(String value) {
            addCriterion("test_delete_sql not like", value, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlIn(List<String> values) {
            addCriterion("test_delete_sql in", values, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlNotIn(List<String> values) {
            addCriterion("test_delete_sql not in", values, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlBetween(String value1, String value2) {
            addCriterion("test_delete_sql between", value1, value2, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteSqlNotBetween(String value1, String value2) {
            addCriterion("test_delete_sql not between", value1, value2, "testDeleteSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlIsNull() {
            addCriterion("test_delete_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlIsNotNull() {
            addCriterion("test_delete_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlEqualTo(String value) {
            addCriterion("test_delete_rollback_sql =", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlNotEqualTo(String value) {
            addCriterion("test_delete_rollback_sql <>", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlGreaterThan(String value) {
            addCriterion("test_delete_rollback_sql >", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("test_delete_rollback_sql >=", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlLessThan(String value) {
            addCriterion("test_delete_rollback_sql <", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("test_delete_rollback_sql <=", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlLike(String value) {
            addCriterion("test_delete_rollback_sql like", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlNotLike(String value) {
            addCriterion("test_delete_rollback_sql not like", value, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlIn(List<String> values) {
            addCriterion("test_delete_rollback_sql in", values, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlNotIn(List<String> values) {
            addCriterion("test_delete_rollback_sql not in", values, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlBetween(String value1, String value2) {
            addCriterion("test_delete_rollback_sql between", value1, value2, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andTestDeleteRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("test_delete_rollback_sql not between", value1, value2, "testDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlIsNull() {
            addCriterion("pd_create_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlIsNotNull() {
            addCriterion("pd_create_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlEqualTo(String value) {
            addCriterion("pd_create_sql =", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlNotEqualTo(String value) {
            addCriterion("pd_create_sql <>", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlGreaterThan(String value) {
            addCriterion("pd_create_sql >", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_create_sql >=", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlLessThan(String value) {
            addCriterion("pd_create_sql <", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_create_sql <=", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlLike(String value) {
            addCriterion("pd_create_sql like", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlNotLike(String value) {
            addCriterion("pd_create_sql not like", value, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlIn(List<String> values) {
            addCriterion("pd_create_sql in", values, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlNotIn(List<String> values) {
            addCriterion("pd_create_sql not in", values, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlBetween(String value1, String value2) {
            addCriterion("pd_create_sql between", value1, value2, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateSqlNotBetween(String value1, String value2) {
            addCriterion("pd_create_sql not between", value1, value2, "pdCreateSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlIsNull() {
            addCriterion("pd_create_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlIsNotNull() {
            addCriterion("pd_create_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlEqualTo(String value) {
            addCriterion("pd_create_rollback_sql =", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlNotEqualTo(String value) {
            addCriterion("pd_create_rollback_sql <>", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlGreaterThan(String value) {
            addCriterion("pd_create_rollback_sql >", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_create_rollback_sql >=", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlLessThan(String value) {
            addCriterion("pd_create_rollback_sql <", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_create_rollback_sql <=", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlLike(String value) {
            addCriterion("pd_create_rollback_sql like", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlNotLike(String value) {
            addCriterion("pd_create_rollback_sql not like", value, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlIn(List<String> values) {
            addCriterion("pd_create_rollback_sql in", values, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlNotIn(List<String> values) {
            addCriterion("pd_create_rollback_sql not in", values, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlBetween(String value1, String value2) {
            addCriterion("pd_create_rollback_sql between", value1, value2, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdCreateRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("pd_create_rollback_sql not between", value1, value2, "pdCreateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlIsNull() {
            addCriterion("pd_alter_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlIsNotNull() {
            addCriterion("pd_alter_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlEqualTo(String value) {
            addCriterion("pd_alter_sql =", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlNotEqualTo(String value) {
            addCriterion("pd_alter_sql <>", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlGreaterThan(String value) {
            addCriterion("pd_alter_sql >", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_alter_sql >=", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlLessThan(String value) {
            addCriterion("pd_alter_sql <", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_alter_sql <=", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlLike(String value) {
            addCriterion("pd_alter_sql like", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlNotLike(String value) {
            addCriterion("pd_alter_sql not like", value, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlIn(List<String> values) {
            addCriterion("pd_alter_sql in", values, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlNotIn(List<String> values) {
            addCriterion("pd_alter_sql not in", values, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlBetween(String value1, String value2) {
            addCriterion("pd_alter_sql between", value1, value2, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterSqlNotBetween(String value1, String value2) {
            addCriterion("pd_alter_sql not between", value1, value2, "pdAlterSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlIsNull() {
            addCriterion("pd_alter_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlIsNotNull() {
            addCriterion("pd_alter_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlEqualTo(String value) {
            addCriterion("pd_alter_rollback_sql =", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlNotEqualTo(String value) {
            addCriterion("pd_alter_rollback_sql <>", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlGreaterThan(String value) {
            addCriterion("pd_alter_rollback_sql >", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_alter_rollback_sql >=", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlLessThan(String value) {
            addCriterion("pd_alter_rollback_sql <", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_alter_rollback_sql <=", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlLike(String value) {
            addCriterion("pd_alter_rollback_sql like", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlNotLike(String value) {
            addCriterion("pd_alter_rollback_sql not like", value, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlIn(List<String> values) {
            addCriterion("pd_alter_rollback_sql in", values, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlNotIn(List<String> values) {
            addCriterion("pd_alter_rollback_sql not in", values, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlBetween(String value1, String value2) {
            addCriterion("pd_alter_rollback_sql between", value1, value2, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdAlterRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("pd_alter_rollback_sql not between", value1, value2, "pdAlterRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlIsNull() {
            addCriterion("pd_update_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlIsNotNull() {
            addCriterion("pd_update_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlEqualTo(String value) {
            addCriterion("pd_update_sql =", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlNotEqualTo(String value) {
            addCriterion("pd_update_sql <>", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlGreaterThan(String value) {
            addCriterion("pd_update_sql >", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_update_sql >=", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlLessThan(String value) {
            addCriterion("pd_update_sql <", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_update_sql <=", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlLike(String value) {
            addCriterion("pd_update_sql like", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlNotLike(String value) {
            addCriterion("pd_update_sql not like", value, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlIn(List<String> values) {
            addCriterion("pd_update_sql in", values, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlNotIn(List<String> values) {
            addCriterion("pd_update_sql not in", values, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlBetween(String value1, String value2) {
            addCriterion("pd_update_sql between", value1, value2, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateSqlNotBetween(String value1, String value2) {
            addCriterion("pd_update_sql not between", value1, value2, "pdUpdateSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlIsNull() {
            addCriterion("pd_update_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlIsNotNull() {
            addCriterion("pd_update_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlEqualTo(String value) {
            addCriterion("pd_update_rollback_sql =", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlNotEqualTo(String value) {
            addCriterion("pd_update_rollback_sql <>", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlGreaterThan(String value) {
            addCriterion("pd_update_rollback_sql >", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_update_rollback_sql >=", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlLessThan(String value) {
            addCriterion("pd_update_rollback_sql <", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_update_rollback_sql <=", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlLike(String value) {
            addCriterion("pd_update_rollback_sql like", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlNotLike(String value) {
            addCriterion("pd_update_rollback_sql not like", value, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlIn(List<String> values) {
            addCriterion("pd_update_rollback_sql in", values, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlNotIn(List<String> values) {
            addCriterion("pd_update_rollback_sql not in", values, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlBetween(String value1, String value2) {
            addCriterion("pd_update_rollback_sql between", value1, value2, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdUpdateRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("pd_update_rollback_sql not between", value1, value2, "pdUpdateRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlIsNull() {
            addCriterion("pd_insert_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlIsNotNull() {
            addCriterion("pd_insert_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlEqualTo(String value) {
            addCriterion("pd_insert_sql =", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlNotEqualTo(String value) {
            addCriterion("pd_insert_sql <>", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlGreaterThan(String value) {
            addCriterion("pd_insert_sql >", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_insert_sql >=", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlLessThan(String value) {
            addCriterion("pd_insert_sql <", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_insert_sql <=", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlLike(String value) {
            addCriterion("pd_insert_sql like", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlNotLike(String value) {
            addCriterion("pd_insert_sql not like", value, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlIn(List<String> values) {
            addCriterion("pd_insert_sql in", values, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlNotIn(List<String> values) {
            addCriterion("pd_insert_sql not in", values, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlBetween(String value1, String value2) {
            addCriterion("pd_insert_sql between", value1, value2, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertSqlNotBetween(String value1, String value2) {
            addCriterion("pd_insert_sql not between", value1, value2, "pdInsertSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlIsNull() {
            addCriterion("pd_insert_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlIsNotNull() {
            addCriterion("pd_insert_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlEqualTo(String value) {
            addCriterion("pd_insert_rollback_sql =", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlNotEqualTo(String value) {
            addCriterion("pd_insert_rollback_sql <>", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlGreaterThan(String value) {
            addCriterion("pd_insert_rollback_sql >", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_insert_rollback_sql >=", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlLessThan(String value) {
            addCriterion("pd_insert_rollback_sql <", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_insert_rollback_sql <=", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlLike(String value) {
            addCriterion("pd_insert_rollback_sql like", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlNotLike(String value) {
            addCriterion("pd_insert_rollback_sql not like", value, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlIn(List<String> values) {
            addCriterion("pd_insert_rollback_sql in", values, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlNotIn(List<String> values) {
            addCriterion("pd_insert_rollback_sql not in", values, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlBetween(String value1, String value2) {
            addCriterion("pd_insert_rollback_sql between", value1, value2, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdInsertRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("pd_insert_rollback_sql not between", value1, value2, "pdInsertRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlIsNull() {
            addCriterion("pd_delete_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlIsNotNull() {
            addCriterion("pd_delete_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlEqualTo(String value) {
            addCriterion("pd_delete_sql =", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlNotEqualTo(String value) {
            addCriterion("pd_delete_sql <>", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlGreaterThan(String value) {
            addCriterion("pd_delete_sql >", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_delete_sql >=", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlLessThan(String value) {
            addCriterion("pd_delete_sql <", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_delete_sql <=", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlLike(String value) {
            addCriterion("pd_delete_sql like", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlNotLike(String value) {
            addCriterion("pd_delete_sql not like", value, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlIn(List<String> values) {
            addCriterion("pd_delete_sql in", values, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlNotIn(List<String> values) {
            addCriterion("pd_delete_sql not in", values, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlBetween(String value1, String value2) {
            addCriterion("pd_delete_sql between", value1, value2, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteSqlNotBetween(String value1, String value2) {
            addCriterion("pd_delete_sql not between", value1, value2, "pdDeleteSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlIsNull() {
            addCriterion("pd_delete_rollback_sql is null");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlIsNotNull() {
            addCriterion("pd_delete_rollback_sql is not null");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlEqualTo(String value) {
            addCriterion("pd_delete_rollback_sql =", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlNotEqualTo(String value) {
            addCriterion("pd_delete_rollback_sql <>", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlGreaterThan(String value) {
            addCriterion("pd_delete_rollback_sql >", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlGreaterThanOrEqualTo(String value) {
            addCriterion("pd_delete_rollback_sql >=", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlLessThan(String value) {
            addCriterion("pd_delete_rollback_sql <", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlLessThanOrEqualTo(String value) {
            addCriterion("pd_delete_rollback_sql <=", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlLike(String value) {
            addCriterion("pd_delete_rollback_sql like", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlNotLike(String value) {
            addCriterion("pd_delete_rollback_sql not like", value, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlIn(List<String> values) {
            addCriterion("pd_delete_rollback_sql in", values, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlNotIn(List<String> values) {
            addCriterion("pd_delete_rollback_sql not in", values, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlBetween(String value1, String value2) {
            addCriterion("pd_delete_rollback_sql between", value1, value2, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andPdDeleteRollbackSqlNotBetween(String value1, String value2) {
            addCriterion("pd_delete_rollback_sql not between", value1, value2, "pdDeleteRollbackSql");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("created_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("created_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("created_user =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("created_user <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("created_user >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("created_user >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("created_user <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("created_user <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("created_user like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("created_user not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("created_user in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("created_user not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("created_user between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("created_user not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNull() {
            addCriterion("modified_user is null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNotNull() {
            addCriterion("modified_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserEqualTo(String value) {
            addCriterion("modified_user =", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotEqualTo(String value) {
            addCriterion("modified_user <>", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThan(String value) {
            addCriterion("modified_user >", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThanOrEqualTo(String value) {
            addCriterion("modified_user >=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThan(String value) {
            addCriterion("modified_user <", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThanOrEqualTo(String value) {
            addCriterion("modified_user <=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLike(String value) {
            addCriterion("modified_user like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotLike(String value) {
            addCriterion("modified_user not like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIn(List<String> values) {
            addCriterion("modified_user in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotIn(List<String> values) {
            addCriterion("modified_user not in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserBetween(String value1, String value2) {
            addCriterion("modified_user between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotBetween(String value1, String value2) {
            addCriterion("modified_user not between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andExt1IsNull() {
            addCriterion("ext1 is null");
            return (Criteria) this;
        }

        public Criteria andExt1IsNotNull() {
            addCriterion("ext1 is not null");
            return (Criteria) this;
        }

        public Criteria andExt1EqualTo(String value) {
            addCriterion("ext1 =", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotEqualTo(String value) {
            addCriterion("ext1 <>", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThan(String value) {
            addCriterion("ext1 >", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThanOrEqualTo(String value) {
            addCriterion("ext1 >=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThan(String value) {
            addCriterion("ext1 <", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThanOrEqualTo(String value) {
            addCriterion("ext1 <=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Like(String value) {
            addCriterion("ext1 like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotLike(String value) {
            addCriterion("ext1 not like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1In(List<String> values) {
            addCriterion("ext1 in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotIn(List<String> values) {
            addCriterion("ext1 not in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Between(String value1, String value2) {
            addCriterion("ext1 between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotBetween(String value1, String value2) {
            addCriterion("ext1 not between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt2IsNull() {
            addCriterion("ext2 is null");
            return (Criteria) this;
        }

        public Criteria andExt2IsNotNull() {
            addCriterion("ext2 is not null");
            return (Criteria) this;
        }

        public Criteria andExt2EqualTo(String value) {
            addCriterion("ext2 =", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotEqualTo(String value) {
            addCriterion("ext2 <>", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThan(String value) {
            addCriterion("ext2 >", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThanOrEqualTo(String value) {
            addCriterion("ext2 >=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThan(String value) {
            addCriterion("ext2 <", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThanOrEqualTo(String value) {
            addCriterion("ext2 <=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Like(String value) {
            addCriterion("ext2 like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotLike(String value) {
            addCriterion("ext2 not like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2In(List<String> values) {
            addCriterion("ext2 in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotIn(List<String> values) {
            addCriterion("ext2 not in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Between(String value1, String value2) {
            addCriterion("ext2 between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotBetween(String value1, String value2) {
            addCriterion("ext2 not between", value1, value2, "ext2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement_data
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 21 12:00:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement_data
     *
     * @mbggenerated Sat Jul 21 12:00:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}